name: koodiarana
description: "Koodiarana by Brice"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  firebase_core: ^3.2.0
  google_fonts: ^6.2.1
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  geolocator: ^12.0.0
  provider: ^6.1.2
  connectivity_plus: ^6.0.4
  flutter_cache_manager: ^3.4.0
  flutter_map_tile_caching: ^9.1.1
  cupertino_icons: ^1.0.6
  flutter_map_animations: ^0.7.0
  flutter_map_cache: ^1.5.1
  http: ^1.2.2
  go_router: ^14.2.3
  fluttertoast: ^8.2.8
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.2.0+3
  loading_animation_widget: ^1.2.1
  shadcn_ui: ^0.9.5
  font_awesome_flutter: ^10.7.0
  shadcn_flutter: ^0.0.20
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  web_socket_channel: ^3.0.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Logo_koodiarana.png" # Assurez-vous d'avoir une image PNG ou JPG ici
  android_icon_name: "ic_launcher"
  ios_icon_name: "AppIcon"
flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logo.jpeg
    - assets/Logo_koodiarana.png
    - assets/Accueil.jpeg
    - assets/google.png
fonts:
    - family: RadixIcons
      fonts:
        - asset: "packages/shadcn_flutter/icons/RadixIcons.otf"
    - family: BootstrapIcons
      fonts:
        - asset: "packages/shadcn_flutter/icons/BootstrapIcons.otf"
    - family: "GeistSans"
      fonts:
        - asset: "packages/shadcn_flutter/fonts/Geist-Black.otf"
          weight: 800
        - asset: "packages/shadcn_flutter/fonts/Geist-Bold.otf"
          weight: 700
        - asset: "packages/shadcn_flutter/fonts/Geist-Light.otf"
          weight: 300
        - asset: "packages/shadcn_flutter/fonts/Geist-Medium.otf"
          weight: 500
        - asset: "packages/shadcn_flutter/fonts/Geist-SemiBold.otf"
          weight: 600
        - asset: "packages/shadcn_flutter/fonts/Geist-Thin.otf"
          weight: 100
        - asset: "packages/shadcn_flutter/fonts/Geist-UltraBlack.otf"
          weight: 900
        - asset: "packages/shadcn_flutter/fonts/Geist-UltraLight.otf"
          weight: 200
        - asset: "packages/shadcn_flutter/fonts/Geist-Regular.otf"
          weight: 400
    - family: "GeistMono"
      fonts:
        - asset: "packages/shadcn_flutter/fonts/GeistMono-Black.otf"
          weight: 800
        - asset: "packages/shadcn_flutter/fonts/GeistMono-Bold.otf"
          weight: 700
        - asset: "packages/shadcn_flutter/fonts/GeistMono-Light.otf"
          weight: 300
        - asset: "packages/shadcn_flutter/fonts/GeistMono-Medium.otf"
          weight: 500
        - asset: "packages/shadcn_flutter/fonts/GeistMono-Regular.otf"
          weight: 400
        - asset: "packages/shadcn_flutter/fonts/GeistMono-SemiBold.otf"
          weight: 600
        - asset: "packages/shadcn_flutter/fonts/GeistMono-Thin.otf"
          weight: 100
        - asset: "packages/shadcn_flutter/fonts/GeistMono-UltraBlack.otf"
          weight: 900
        - asset: "packages/shadcn_flutter/fonts/GeistMono-UltraLight.otf"
          weight: 200