// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxxu2_EJxvHbdH1elQNBAUUJ4lHUStNok',
    appId: '1:647846580943:web:214019d9198d5fa9831dba',
    messagingSenderId: '647846580943',
    projectId: 'koodiarana-b7bd5',
    authDomain: 'koodiarana-b7bd5.firebaseapp.com',
    storageBucket: 'koodiarana-b7bd5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMpddRhRAy2eRFs_tAQoQ7GHEkUHCgn00',
    appId: '1:647846580943:android:dd7e3999495443d8831dba',
    messagingSenderId: '647846580943',
    projectId: 'koodiarana-b7bd5',
    storageBucket: 'koodiarana-b7bd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2vlNcslFxRaO4i2JBKrPrlAcwVXc-wb0',
    appId: '1:647846580943:ios:e4641f9d768a78a3831dba',
    messagingSenderId: '647846580943',
    projectId: 'koodiarana-b7bd5',
    storageBucket: 'koodiarana-b7bd5.appspot.com',
    iosBundleId: 'com.example.koodiarana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2vlNcslFxRaO4i2JBKrPrlAcwVXc-wb0',
    appId: '1:647846580943:ios:e4641f9d768a78a3831dba',
    messagingSenderId: '647846580943',
    projectId: 'koodiarana-b7bd5',
    storageBucket: 'koodiarana-b7bd5.appspot.com',
    iosBundleId: 'com.example.koodiarana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxxu2_EJxvHbdH1elQNBAUUJ4lHUStNok',
    appId: '1:647846580943:web:b51072cbb56182b8831dba',
    messagingSenderId: '647846580943',
    projectId: 'koodiarana-b7bd5',
    authDomain: 'koodiarana-b7bd5.firebaseapp.com',
    storageBucket: 'koodiarana-b7bd5.appspot.com',
  );
}
